name: Build

on:
  workflow_dispatch:
    inputs:
      game_package:
        description: 'Game Package Name'
        required: true
        default: 'com.example.game'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set game package name
      run: |
        sed -i 's/#define GamePackageName ".*"/#define GamePackageName "${{ github.event.inputs.game_package }}"/' module/src/main/cpp/game.h
    
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew module:assembleRelease
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Zygisk-Il2CppDumper
        path: out/*.zip
